/*
 * This source file was generated by the Gradle 'init' task
 */
package loyalcustomer;

import static org.junit.jupiter.api.Assertions.*;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Test;

class AppTest {
    LoyalCustomer classToBeTested;

    @Test
    void getLoyalCustomersListTest() {
        classToBeTested = new LoyalCustomer();
        String[] path = {
                "C:\\Users\\j_eik\\OneDrive\\Documents\\Resume\\AssesmentQuestions\\DELMARAssesment\\LogFiles" };
        List<Integer> actualLoyalCustomerList = classToBeTested.getLoyalCustomersList(path);
        List<Integer> expectedLoyalCustomerList = new ArrayList<>(Arrays.asList(1, 2, 4, 7));
        assertEquals(expectedLoyalCustomerList, actualLoyalCustomerList);
    }

    @Test
    void generateReportTest() {
        classToBeTested = new LoyalCustomer();

        List<Integer> data = new ArrayList<>(Arrays.asList(1, 2, 4, 7));

        String fileName = "LoyalCustomers.log";
        String folderName = "LoyalCustomers";
        String path = "C:\\Users\\j_eik\\OneDrive\\Documents\\Resume\\AssesmentQuestions\\DELMARAssesment\\LogFiles";
        String folderPath = path + File.separator + folderName;
        String fullPath = path + File.separator + folderName + File.separator + fileName;

        classToBeTested.generateReport(data, fileName, folderPath);

        File folderToCheck = new File(folderPath);
        File fileToCheck = new File(fullPath);

        boolean folderExists = folderToCheck.exists();
        assertTrue(folderExists);

        boolean fileExists = fileToCheck.exists();
        assertTrue(fileExists);

        String nextLine;

        try (FileReader fileReader = new FileReader(fullPath);
                BufferedReader bufferedReader = new BufferedReader(fileReader)) {
                    nextLine = bufferedReader.readLine();
                    String expectingHeader = "Here are the customer IDs of the loyal customers:";
                    assertEquals(nextLine, expectingHeader);

                    nextLine = bufferedReader.readLine();
                    String expectingBlank = "";
                    assertEquals(expectingBlank, nextLine);
                    
                    nextLine = bufferedReader.readLine();
                    String expectedCustomer1 = "Customer: 1";
                    assertEquals(expectedCustomer1, nextLine);

                    nextLine = bufferedReader.readLine();
                    String expectedCustomer2 = "Customer: 2";
                    assertEquals(expectedCustomer2, nextLine);

                    nextLine = bufferedReader.readLine();
                    String expectedCustomer3 = "Customer: 4";
                    assertEquals(expectedCustomer3, nextLine);

                    nextLine = bufferedReader.readLine();
                    String expectedCustomer4 = "Customer: 7";
                    assertEquals(expectedCustomer4, nextLine);

                    nextLine = bufferedReader.readLine();
                    assertNull(nextLine);
        } catch(IOException ioe){
            assert(false);
        }
    }
}
